export type ProcessType = "Spunbond" | "Meltblown";

export type ProblemCategory = 
  | "Web Formation" 
  | "Bonding" 
  | "Finishing" 
  | "Equipment" 
  | "Quality";

export interface Problem {
  id: string;
  title: string;
  category: ProblemCategory;
  processType: ProcessType;
  description: string;
  causes: string[];
  solutions: string[];
  severity: "high" | "medium" | "low";
}

export const NONWOVEN_PROBLEMS: Problem[] = [
  {
    id: "1",
    title: 'Basis Weight Distribution Shows "Smiley" Pattern',
    category: "Web Formation",
    processType: "Spunbond",
    description: "Irregular basis weight distribution across the web width showing a smiley pattern (up or down).",
    severity: "high",
    causes: [
      "Incorrect SAS-plate heater temperature",
      "Sealing not completely inflated or damaged",
      "Seal die-cabin leakage",
      "Seal cabin-intermediate channel issues",
      "Seal intermediate channel-compensator problems (RF3 system)",
      "Honeycombs and perforated screens of quench chamber dirty or damaged",
      "Suction box dirty",
      "Diffuser malfunction",
      "Ambient air gap dirty",
      "Sheet position incorrect",
    ],
    solutions: [
      "Check and adjust SAS-plate heater temperature (if smiley up or down)",
      "Inspect and replace damaged inflatable seals",
      "Verify seal integrity between die-cabin, cabin-intermediate channel",
      "Check compensator seals (RF3 systems only)",
      "Clean honeycombs and perforated screens in quench chamber",
      "Clean suction box thoroughly",
      "Inspect and adjust diffuser settings",
      "Clean ambient air gap and diffuser",
      "Correct sheet position",
    ],
  },
  {
    id: "2",
    title: "Blow Backs / Eye Brows in Fabric",
    category: "Web Formation",
    processType: "Spunbond",
    description: "Blow backs or eye brow patterns appearing in the fabric during production.",
    severity: "high",
    causes: [
      "Wrong ratio of suction air fans",
      "Lifting at press roll",
      "Suction boxes dirty (RF3 systems)",
      "Suction drawer plate dirty",
      "Conveyor belt dirty",
      "Press roll not properly closed or incorrect pressure",
      "Press roll temperature too low (less prebonding) or too high (lifting)",
      "Support roll surface damaged or sticky",
      "Air flow rate too high blowing on incoming fabric",
    ],
    solutions: [
      "If smiley backwards: decrease main suction air fan, increase fixing air fan",
      "If smiley forward: increase main suction air fan, decrease fixing air fan",
      "Increase fixing air fan revolution if blow backs appear after press roll",
      "Clean suction boxes (RF3 systems)",
      "Clean suction drawer plate and conveyor belt",
      "Properly close press roll and adjust pressure",
      "Optimize press roll temperature (minimum 110°C)",
      "Check and clean support roll surface",
      "Increase suction air fan speed or decrease cooling air fan/cabin pressure",
    ],
  },
  {
    id: "3",
    title: "Holes in Fabric",
    category: "Quality",
    processType: "Spunbond",
    description: "Holes appearing in the nonwoven fabric during production.",
    severity: "high",
    causes: [
      "Drips from spinneret",
      "Press roll surface damaged",
      "Monomer drips on press roll surface",
      "Polymer drips on press roll surface",
      "Press roll too cold",
      "Drips on conveyor belt",
      "Broken meshes in conveyor belt",
      "Rough surface on conveyor belt",
      "Belt mesh size too large",
      "Holes in conveyor belt",
    ],
    solutions: [
      "Check and clean spinneret to prevent drips",
      "Inspect and repair/replace damaged press roll surface",
      "Clean press roll and monomer exhauster",
      "Increase press roll temperature (minimum 110°C)",
      "Clean conveyor belt and remove drips",
      "Repair broken meshes in belt",
      "Use fine sandpaper (> 800 c/cm²) to smooth rough belt surface",
      "Change to finer mesh belt type",
      "Repair or replace damaged conveyor belt",
    ],
  },
  {
    id: "4",
    title: "Drips in Production",
    category: "Equipment",
    processType: "Spunbond",
    description: "Polymer or monomer drips occurring during the spunbond process.",
    severity: "high",
    causes: [
      "Spinneret temperature issues",
      "Polymer contamination",
      "Improper extrusion conditions",
      "Monomer exhauster dirty or insufficient",
      "Die temperature incorrect",
    ],
    solutions: [
      "Optimize spinneret temperature",
      "Check polymer quality and filtration",
      "Adjust extrusion temperature according to MFR",
      "Clean monomer exhauster system",
      "Verify and adjust die temperature settings",
    ],
  },
  {
    id: "5",
    title: "Thin Spots / Low Weight Areas",
    category: "Web Formation",
    processType: "Spunbond",
    description: "Localized areas with lower than normal basis weight in the fabric.",
    severity: "medium",
    causes: [
      "Capillary running bad",
      "Honeycombs dirty",
      "Ambient air gap dirty",
      "Channel sheets dirty",
      "Conveyor belt issues",
      "Diffuser setting incorrect",
    ],
    solutions: [
      "Plug bad capillary with sharp pencil class HB5",
      "Clean honeycombs and perforated screens",
      "Clean ambient air gap and diffuser",
      "Clean all channel sheets",
      "Check and clean conveyor belt",
      "Correct diffuser setup",
    ],
  },
  {
    id: "6",
    title: "Width of Web Too Small (RF4)",
    category: "Web Formation",
    processType: "Spunbond",
    description: "The nonwoven web width is narrower than desired in RF4 systems.",
    severity: "medium",
    causes: [
      "Prediffuser opened too wide",
      "Diffuser angle too wide",
      "Insufficient air volume for configuration",
      "Distance diffuser-conveyor belt too large",
      "Tension of kiss roll/dryer/winder too high",
    ],
    solutions: [
      "Reduce outlet gap of diffuser",
      "Open diffuser in upper part",
      "Increase cabin pressure if possible",
      "Decrease distance diffuser-conveyor belt for more secondary air",
      "Check speed ratio of drives",
      "Check and adjust winder tension force",
    ],
  },
  {
    id: "7",
    title: "Hard Pieces in Fabric",
    category: "Quality",
    processType: "Spunbond",
    description: "Hard pieces or stiff areas appearing in the nonwoven fabric.",
    severity: "medium",
    causes: [
      "Monomer exhauster closed too much",
      "Extrusion temperature too high",
      "Die temperature too high",
      "Quench air temperature too high",
      "SAS-gap too closed",
      "Damage of honeycomb in upper area (for hard piece streets)",
      "Dirt on honeycomb (for hard piece streets)",
      "Leakage of inflatable seal (for hard piece streets)",
      "Leakage of monomer frame (for hard piece streets)",
    ],
    solutions: [
      "Open monomer exhauster",
      "Reduce extrusion temperature",
      "Reduce die temperature",
      "Reduce quench air temperature (upper and/or lower)",
      "Open SAS-gap for more cooling air (monitor spinning stability)",
      "Inspect and repair damaged honeycomb in upper area",
      "Clean honeycombs thoroughly",
      "Check and repair inflatable seal leakage",
      "Repair monomer frame leakage",
    ],
  },
  {
    id: "8",
    title: "Stripes in Fabric",
    category: "Quality",
    processType: "Spunbond",
    description: "Vertical or horizontal stripes visible in the finished fabric.",
    severity: "medium",
    causes: [
      "Inflatable seals not correctly inflated",
      "Area of seals dirty",
      "Inflatable seals damaged",
      "Seal SAS-plates-prediffuser damaged (RF4)",
      "Leakage in die insulation causing cold spot",
      "Die body heating cartridge defect",
      "Monomer exhauster dirty with insufficient throughput",
      "Dirty or damaged honeycombs",
      "Suction box dirty (RF3)",
      "Suction drawer plate dirty (RF4)",
      "Damaged lower support roll",
      "Nip not closed over complete width",
      "Conveyor belt dirty",
    ],
    solutions: [
      "Check and properly inflate all seals",
      "Clean seal areas thoroughly",
      "Check leakage monitor and replace damaged seals",
      "Repair or replace SAS-plates-prediffuser seal (RF4)",
      "Inspect die insulation and repair leakage",
      "Replace defective heating cartridge in die body",
      "Clean monomer exhauster for adequate throughput",
      "Clean or replace damaged honeycombs",
      "Clean suction box (RF3) or drawer plate (RF4)",
      "Repair or replace damaged support roll",
      "Ensure nip is closed completely across width",
      "Clean conveyor belt",
    ],
  },
  {
    id: "9",
    title: "Wrinkles in Product",
    category: "Finishing",
    processType: "Spunbond",
    description: "Wrinkles or folds appearing in the finished nonwoven product.",
    severity: "medium",
    causes: [
      "Speed differences between equipment sections",
      "Poor positioning between spin belt table and calender",
      "Excessive shrinkage from high press roll temperature",
      "Periodic folds from spin belt sealing issues",
      "Press roll temperature or pressure incorrect",
      "Web tension issues",
      "Incorrect roll positioning",
      "Winder stretching/elongation roll problems",
    ],
    solutions: [
      "Check synchronization of all drives",
      "Adjust positioning between spin belt table and calender",
      "Reduce press roll temperature to minimize shrinkage",
      "Inspect spin belt especially at sealing if folds are periodic",
      "Optimize press roll temperature and pressure",
      "Balance web tension throughout system",
      "Check and correct positioning of all rolls",
      "Adjust winder stretching/elongation roll",
    ],
  },
  {
    id: "10",
    title: "Wrap Up at Press Roll",
    category: "Equipment",
    processType: "Spunbond",
    description: "Fabric wrapping around the press roll during production.",
    severity: "high",
    causes: [
      "Press roll surface damaged",
      "Monomer drips on roll surface",
      "Polymer drips on roll surface",
      "Press roll temperature too cold",
      "Monomer exhauster dirty",
    ],
    solutions: [
      "Replace damaged press roll",
      "Clean press roll surface",
      "Clean monomer exhauster system",
      "Increase press roll temperature (minimum 110°C)",
      "Verify heater functionality",
    ],
  },
  {
    id: "11",
    title: "Wrap Up at Calender",
    category: "Equipment",
    processType: "Spunbond",
    description: "Fabric wrapping around calender rolls during bonding process.",
    severity: "high",
    causes: [
      "Embossing/s-roll temperature too high",
      "Edge cooling not efficient",
      "Edge cooling position incorrect",
      "Weak edges of web",
      "Web tension too low between embossing-roll and cooling roll",
      "Web tension lost during roll change at winder",
    ],
    solutions: [
      "Reduce embossing/s-roll temperature",
      "Optimize edge cooling efficiency",
      "Adjust edge cooling position",
      "Strengthen web edges through process adjustments",
      "Increase web tension between embossing-roll and cooling roll",
      "Maintain proper tension during winder roll changes",
    ],
  },
  {
    id: "12",
    title: "Insufficient Tensile Strength / High Elongation",
    category: "Quality",
    processType: "Spunbond",
    description: "Fabric exhibits lower than required tensile strength or excessive elongation.",
    severity: "high",
    causes: [
      "Air flow rate/cabin pressure too low",
      "Cooling air temperature too low",
      "Extrusion temperature not optimized for MFR",
      "Poor calender bonding",
      "Throughput too high",
      "Fiber speed too low",
      "Resin/additive quality issues",
    ],
    solutions: [
      "Increase air flow rate/cabin pressure as much as possible",
      "Increase cooling air temperature as much as possible",
      "Optimize extrusion temperature according to MFR",
      "Optimize calender line pressure and bonding temperatures",
      "Run bonding curve if necessary",
      "Reduce spin pump speed if throughput too high",
      "Reduce SAS-gap to increase fiber speed (adjust RF4 prediffuser too)",
      "Use different resin/additive lot",
      "If elongation too high: increase calender temperature and/or line pressure",
    ],
  },
  {
    id: "13",
    title: "Shrinkage with Heavy Basis Weight (>50 gsm)",
    category: "Quality",
    processType: "Spunbond",
    description: "Excessive shrinkage occurring in heavy basis weight fabrics over 50 gsm.",
    severity: "medium",
    causes: [
      "Press roll temperature too high",
      "Press roll pressure too low",
      "Inadequate prebonding",
    ],
    solutions: [
      "Reduce press roll temperature as much as possible",
      "Set press roll to maximum pressure",
      "Balance temperature and pressure for optimal prebonding",
    ],
  },
  {
    id: "14",
    title: "Hard Fibers in Product",
    category: "Quality",
    processType: "Spunbond",
    description: "Individual hard or stiff fibers present in the fabric.",
    severity: "low",
    causes: [
      "Incomplete fiber drawing",
      "Polymer crystallization",
      "Cooling issues in spinning zone",
      "Quench air distribution problems",
    ],
    solutions: [
      "Optimize quench air temperature and flow",
      "Check cooling air distribution uniformity",
      "Adjust spinning conditions to improve fiber drawing",
      "Verify polymer processing parameters",
    ],
  },
  {
    id: "15",
    title: "Eyebrows in Meltblown",
    category: "Web Formation",
    processType: "Meltblown",
    description: "Eyebrow patterns appearing at the inlet side of meltblown layer in SSMMS production.",
    severity: "high",
    causes: [
      "Air-flow of MB is too high",
      "Suction blower cannot ensure exhausting of all superfluous air",
      "DCD is too narrow causing high air pressure",
      "DCD is too wide causing air stream to spread",
      "Spunbond layer has low-weight areas and is too sensitive",
      "Pressure roll temperature too low (minimum 120°C on A beam)",
      "Conveyor belt has closed area (old drip) preventing exhausting",
      "Suction box drawers are dirty causing vacuum loss",
      "Hot air temperature influence",
      "Spunbond fabric lifts up at pressure roll outlet",
    ],
    solutions: [
      "Reduce meltblown air flow rate",
      "Increase suction blower speed",
      "Adjust DCD to optimal width",
      "Improve spunbond layer weight distribution",
      "Increase pressure roll temperature to at least 120°C for better prebonding",
      "Clean conveyor belt to remove closed areas",
      "Clean suction box drawers to restore vacuum",
      "Adjust hot air temperature",
      "Optimize air stream angle by adjusting valves on MB die body pipes",
      "Set air stream angle in production direction to help eliminate eyebrows",
    ],
  },
  {
    id: "16",
    title: "Flying Fibers",
    category: "Web Formation",
    processType: "Meltblown",
    description: "Loose fibers floating in the air around the meltblown process.",
    severity: "medium",
    causes: [
      "Air flow rate is too high",
      "Extruder/pump off",
      "Throughput too low",
      "Melt temperature too high",
      "Suction blower speed too low",
      "DCD too small",
      "Resin is wet",
      "Air temperature is too high",
    ],
    solutions: [
      "Reduce air flow rate",
      "Check extruder/pump operation",
      "Increase throughput to appropriate level",
      "Reduce melt temperature",
      "Increase suction blower speed",
      "Adjust DCD to larger setting",
      "Ensure resin is properly dried",
      "Reduce air temperature",
    ],
  },
  {
    id: "17",
    title: "Stripes in Machine Direction (MD)",
    category: "Quality",
    processType: "Meltblown",
    description: "Vertical stripes appearing in the meltblown fabric running in machine direction.",
    severity: "high",
    causes: [
      "Air knife or die tip has a defect",
      "Air knife or die tip is covered or plugged with cracked material",
      "Resin is wet",
      "Setback or air gap adjusted badly",
      "Suction box is dirty",
      "Cleaning procedure was imperfect",
      "Capillaries are blocked",
      "Line handling is wrong",
      "Wrong raw material or additives",
    ],
    solutions: [
      "Inspect and repair air knife or die tip defects",
      "Clean air knife and die tip to remove cracked material",
      "Ensure resin is properly dried",
      "Adjust setback and air gap to correct settings",
      "Clean suction box thoroughly",
      "Perform proper cleaning procedure",
      "Clean blocked capillaries",
      "Review and correct line handling procedures",
      "Verify raw material and additive compatibility",
    ],
  },
  {
    id: "18",
    title: "Zebra Stripes in Cross Direction (CD)",
    category: "Quality",
    processType: "Meltblown",
    description: "Horizontal zebra stripe patterns appearing across the fabric width.",
    severity: "medium",
    causes: [
      "High suction",
      "Low air flow",
      "DCD too high",
      "Bad spunbond layer",
    ],
    solutions: [
      "Reduce suction level",
      "Increase air flow rate",
      "Reduce DCD to appropriate level",
      "Improve spunbond layer quality and uniformity",
    ],
  },
  {
    id: "19",
    title: "Shots in Meltblown",
    category: "Quality",
    processType: "Meltblown",
    description: "Hard spots or gel particles appearing in the meltblown fabric.",
    severity: "high",
    causes: [
      "Filter of screen changer is very dirty (even if extruder pressure is normal)",
      "Filter of die tip pack is too dirty (even if pressure is normal)",
      "Cassette needs changing (die pressure >40 bar at 50 kg/h/m throughput)",
      "Resin is wet",
      "Fluctuation in resin quality",
      "Melt temperature too low or too high",
      "Masterbatches not suitable for Melt-Blown",
    ],
    solutions: [
      "Change screen changer filter",
      "Replace die tip pack filter",
      "Change cassette when die pressure exceeds 40 bar at 50 kg/h/m",
      "Ensure proper resin drying",
      "Use consistent quality resin",
      "Optimize melt temperature",
      "Use only masterbatches suitable for Melt-Blown process",
    ],
  },
  {
    id: "20",
    title: "High Throughput Issues (>70 kg/h/m)",
    category: "Quality",
    processType: "Meltblown",
    description: "Quality problems occurring when throughput exceeds 70 kg/h/m.",
    severity: "medium",
    causes: [
      "Throughput exceeding process capability",
      "Insufficient fiber attenuation at high rates",
      "Poor fiber formation at high speeds",
    ],
    solutions: [
      "Reduce throughput to optimal range",
      "Note: High throughput causes fabric to become harsh",
      "Expect higher air permeability",
      "Expect increased fiber diameter",
      "Expect decreased water column",
      "Monitor for shot formation",
    ],
  },
  {
    id: "21",
    title: "DCD Too High",
    category: "Web Formation",
    processType: "Meltblown",
    description: "Die-to-collector distance set too high causing quality issues.",
    severity: "medium",
    causes: [
      "DCD adjusted too far from collector",
      "Fiber lay down spreading too wide",
    ],
    solutions: [
      "Reduce DCD to appropriate level",
      "Note: High DCD causes water column to decrease",
      "Expect higher air permeability",
      "Expect bigger pore size",
      "Expect softer fabric",
      "Caution: In SMS production, too high DCD can destroy spunbond layer",
    ],
  },
  {
    id: "22",
    title: "Air Flow Rate Too Low",
    category: "Web Formation",
    processType: "Meltblown",
    description: "Insufficient air flow rate in meltblown process.",
    severity: "high",
    causes: [
      "Air flow rate set too low",
      "Blower capacity insufficient",
      "Air system restrictions",
    ],
    solutions: [
      "Increase air flow rate to appropriate level",
      "Note: Low air flow causes fabric to become harsh",
      "Expect bigger pore size",
      "Expect higher air permeability",
      "Expect bigger fiber diameter",
    ],
  },
  {
    id: "23",
    title: "Melt Temperature Too Low",
    category: "Equipment",
    processType: "Meltblown",
    description: "Polymer melt temperature below optimal range.",
    severity: "high",
    causes: [
      "Heater settings too low",
      "Temperature control malfunction",
      "Insufficient heating capacity",
    ],
    solutions: [
      "Increase melt temperature to optimal range",
      "Note: Low melt temperature causes fabric to become harsh",
      "Expect bigger pore size",
      "Expect high air permeability",
      "May cause shot formation",
      "Expect big fiber diameter",
      "Will require higher air flow rate (increased power consumption)",
    ],
  },
  {
    id: "24",
    title: "Bad Air Knife/Setback Setup",
    category: "Equipment",
    processType: "Meltblown",
    description: "Improper air knife or setback configuration causing process issues.",
    severity: "high",
    causes: [
      "Air knife gap set incorrectly",
      "Setback distance not optimal",
      "Air knife alignment issues",
      "Fibers touching air knives",
    ],
    solutions: [
      "Cool down the line before adjusting",
      "Correct air knife and setback settings",
      "Consider die cassette change if persistent",
      "Note: May cause shot formation",
      "Expect drops when fibers touch air knives",
      "May cause flying fibers",
      "Recommendation: Use 270°C to 290°C air temperature for standard PP",
      "Note: Changing air temperature alone may not solve the problem",
    ],
  },
];

export const CATEGORIES: ProblemCategory[] = [
  "Web Formation",
  "Bonding",
  "Finishing",
  "Equipment",
  "Quality",
];

export const CATEGORY_COLORS: Record<ProblemCategory, string> = {
  "Web Formation": "#3B82F6",
  "Bonding": "#EF4444",
  "Finishing": "#10B981",
  "Equipment": "#F59E0B",
  "Quality": "#8B5CF6",
};

export const SEVERITY_COLORS = {
  high: "#DC2626",
  medium: "#F59E0B",
  low: "#10B981",
};
